FROM python:3.9-slim

# Cài đặt Java JRE và công cụ cơ bản
RUN apt-get update >/dev/null && \
    apt-get install -y default-jre procps >/dev/null && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Cài đặt PySpark và Numpy
RUN pip install --no-cache-dir pyspark==3.5.0 numpy >/dev/null 2>&1

WORKDIR /app
CMD ["python", "final_project.py"]
